name: Auto Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'github-actions[bot]' || github.event.pull_request.user.login == github.repository_owner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Approve PR
        run: gh pr review "${{ github.event.pull_request.html_url }}" --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        run: gh pr merge "${{ github.event.pull_request.html_url }}" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
